# Configuration de base du framework
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Gestion des sessions
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Log des erreurs PHP
    php_errors:
        log: true

    # Configuration des assets
    asset_mapper:
        paths:
            - '%kernel.project_dir%/public/assets'
        missing_import_mode: strict  # Ou 'warn' en fonction de vos besoins

    # Gestion de l'upload des fichiers (si nécessaire)
    # file_uploads: true

    # Enable Twig, si vous utilisez Twig
    # twig:
    #     default_path: '%kernel.project_dir%/templates'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

    # Vous pouvez ajuster la configuration de la session et d'autres paramètres pour l'environnement de test
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
