vich_uploader:
    db_driver: orm

    mappings:
        profile_pictures:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true